# Generated by Django 4.2.1 on 2023-05-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labSystem', '0002_rename_lab_id_labreport_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Under Maintenance', 'under maintenance')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='report_description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='report_status',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware')], default='Software', max_length=9),
        ),
    ]
